name: testActions

on: [push]

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print start testing
        run: echo "Testing is stirted"
      
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install unittest2
      
      - name: Run tests
        run: python3 calc.py
