name: testAction

on: push
      
jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: git-clone
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
