name: testAction

on: push
      
jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: git-clone
        uses: actions/checkout@v1
        
      - name: git-show
        run : ls -la
