name: testAction

on: push
      
jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: run_build
        uses: actions/checkout@v2.3.1
        with: 
            persist-credentials: false
            
      - name: Install 🔧
        run: npm install

      - name: Run Test 🔨
        run: npm run test

      - name: Build 👷
        run: npm run build
